class PostBackgroundImageController{
  static List<String> bgImages = [
  
  
    'assets/images/PostBackground/1.png',
    'assets/images/PostBackground/2.png',
    'assets/images/PostBackground/3.png',
    'assets/images/PostBackground/4.png',
    'assets/images/PostBackground/5.png',
    'assets/images/PostBackground/6.png',
    'assets/images/PostBackground/7.png',
    'assets/images/PostBackground/8.png',
    'assets/images/PostBackground/9.png',
    'assets/images/PostBackground/10.png',
    'assets/images/PostBackground/11.png',
    'assets/images/PostBackground/12.png',
    'assets/images/PostBackground/13.png',
    'assets/images/PostBackground/14.png',
    'assets/images/PostBackground/15.png',
    'assets/images/PostBackground/16.png',
    'assets/images/PostBackground/17.png',
    'assets/images/PostBackground/18.png',
    'assets/images/PostBackground/19.png',
    'assets/images/PostBackground/20.png',
	'assets/images/PostBackground/21.png',
    'assets/images/PostBackground/22.png',
    'assets/images/PostBackground/23.png',
    'assets/images/PostBackground/24.png',
    'assets/images/PostBackground/25.png',
    'assets/images/PostBackground/26.png',
    'assets/images/PostBackground/27.png',
    'assets/images/PostBackground/28.png',
    'assets/images/PostBackground/29.png',
    'assets/images/PostBackground/30.png',
    'assets/images/PostBackground/31.png',
    'assets/images/PostBackground/32.png',
    'assets/images/PostBackground/33.png',
    'assets/images/PostBackground/34.png',
    'assets/images/PostBackground/35.png',
    'assets/images/PostBackground/36.png',
    'assets/images/PostBackground/37.png',
    'assets/images/PostBackground/38.png',
    'assets/images/PostBackground/39.png',
    'assets/images/PostBackground/40.png',
	'assets/images/PostBackground/41.png',
    'assets/images/PostBackground/42.png',
    'assets/images/PostBackground/43.png',
    'assets/images/PostBackground/44.png',
    'assets/images/PostBackground/45.png',
    'assets/images/PostBackground/46.png',
    'assets/images/PostBackground/47.png',
    'assets/images/PostBackground/48.png',
    'assets/images/PostBackground/49.png',



  ];
}
