name: blabloglucy
description: blabloglucy.

publish_to: 'none'
version: 101.35.0+1011935

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  another_flushbar: ^1.12.29
  avatar_view: ^1.0.1
  clean_api: ^0.2.7
  cupertino_icons: ^1.0.5
#  easy_localization: ^3.0.1
  email_validator: ^2.1.17
#  devicelocale: ^0.5.5
  equatable: ^2.0.5
  flick_video_player: ^0.5.0
  signalr_netcore: ^1.3.3
  airplane_mode_checker: ^1.0.3
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_hooks: ^0.18.5+1
#  flutter_localizations:
#    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  flutter_widget_from_html: ^0.9.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  hooks_riverpod: ^2.1.1
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  video_player: ^2.4.7
#  volume: ^1.0.1
  get_storage: ^2.0.3
  otp_timer_button: ^1.1.0
  connectivity_plus: ^3.0.2

  account_picker: ^2.0.0

  # I am using Provider for State Management
  provider: ^6.0.4
  bot_toast: ^4.0.3
  bloc: ^8.1.0
  socket_io_client: ^2.0.0
  loadmore: ^2.0.1
  cached_network_image: ^3.2.2
  url_launcher: ^6.1.6
  readmore: ^2.2.0
  change_app_package_name: ^1.1.0
  intl: ^0.18.0
  syncfusion_flutter_charts: ^20.3.57
  flutter_localization: ^0.1.10
  easy_localization: ^3.0.2-dev.2

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.14
  flutter_test:
    sdk: flutter
flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/1024.png"
  adaptive_icon_background: "assets/images/1024.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true

  assets:
    - assets/images/PostBackground/
    - assets/icons/
    - assets/icons/logo_text.svg
    - assets/images/
    - assets/images/consult/
    - assets/images/background.jpg
    - assets/videos/
    - assets/translations/
    - assets/translations/en.json
    - assets/translations/he.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
